=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc2-WS/assignments/CST6445Assignment3v2.xsd
<?xml version="1.0"?>
<!--

ASSIGNMENT #3

Author: Rob Morton
Date:   2011-11-26 

  Subscriber XSD

-->
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:s="http://www.subscriber.org"
	targetNamespace="http://www.subscriber.org" 	
	elementFormDefault="qualified">
	<element name="subscriber">
        <complexType>
			<sequence>
				<element name="id" type="s:idType" minOccurs="1" maxOccurs="1" />
				<element name="policy" type="string" minOccurs="0" maxOccurs="1" />
				<element name="subscriptionstartdate" type="string" minOccurs="1" maxOccurs="1" />
				<element name="locations" type="s:locationsType" minOccurs="1" maxOccurs="unbounded" />
				<!-- <element name="bob" type="string" minOccurs="1" maxOccurs="1" /> -->
			</sequence>
			<attribute name="type" type="string" fixed="internal" />
		</complexType>
    </element>
	
	<complexType name="idType">
		<sequence>
			<element name="imsi" type="s:imsiType" minOccurs="1" maxOccurs="1" />
			<element name="other1" type="s:other1Type" minOccurs="0" maxOccurs="1" />
			<element name="other2" type="s:other2Type" minOccurs="0" maxOccurs="1" />
			<element name="other3" type="s:other3Type" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>
	
	<simpleType name="imsiType">
	  <restriction base="integer">
	    <totalDigits value="10" />
	  </restriction>
	</simpleType>

	<simpleType name="other1Type">
	  <restriction base="integer">
	    <minInclusive value="0" />
	    <maxInclusive value="1000000000" />	    
	  </restriction>
	</simpleType>

	<simpleType name="other2Type">
	  <restriction base="string">
	    <minLength value="5" />
	    <maxLength value="8" />
	  </restriction>
	</simpleType>

	<simpleType name="other3Type">
	  <restriction base="string">
        <length value="19" fixed="true"/>
        <pattern value="[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}"/>
	  </restriction>
	</simpleType>

	<complexType name="locationsType">
		<sequence>
			<element name="location" type="s:locationType" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<complexType name="locationType">
		<sequence>
			<element name="logical" type="string" minOccurs="1" maxOccurs="1" />
			<element name="physical" type="s:physicalType" minOccurs="1" maxOccurs="1" />
		</sequence>
	</complexType>
	
	<complexType name="physicalType">
		<sequence>
			<element name="streetaddress" type="string" minOccurs="1" maxOccurs="1" />
			<element name="city" type="string" minOccurs="1" maxOccurs="1" />
			<element name="stateorprov" type="string" minOccurs="0" maxOccurs="1" />
			<element name="code" type="s:codeType" minOccurs="1" maxOccurs="1" />
		</sequence>
	</complexType>
	
	<complexType name="codeType">
		<sequence>
			<element name="basicCode" type="string" minOccurs="1" maxOccurs="1" />
		</sequence>
		<attribute name="country" type="string" />
	</complexType>
	
</schema>

=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc2-WS/assignments/CST6445Assignment1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--

ASSIGNMENT #1 (re-written slightly to handle validation for assignment #3)

Author: Rob Morton
Date:   2011-11-17 

A subscriber is a business object which represents and end user of the 'system'

Subscribers are identified by their ID which can be one or more of three things: IMSI,other1 and other2.
They contain information regarding the policy applied to the subscriber by the 'system' as well as the location(s)
of the given subscriber
-->
<subscriber type='internal'
    xmlns="http://www.subscriber.org"
    xmlns:bob="http://www.bob.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.subscriber.org 
	                    file:D:\nms_build_root\JavaMisc2-WS\assignments\CST6445Assignment3v2.xsd">
	<id>
		<imsi>1234567890</imsi>
		<other3>1234 5678 9012 3456</other3>
	</id>
	<subscriptionstartdate>2011-11-10</subscriptionstartdate>
	<locations>
		<location>
			<logical>cct1234567890</logical>
			<physical>
				<streetaddress>123 abc str</streetaddress>
				<city>abc</city>
				<stateorprov>blah</stateorprov>
				<code country='CA'>
					<basicCode>k3j 2g5</basicCode>
				</code>
			</physical>
		</location>
		<location>
			<logical>cct1234567891</logical>
			<physical>
				<streetaddress>456 abc str</streetaddress>
				<city>def</city>
				<code country='US'>
					<basicCode>12345</basicCode>
				</code>
			</physical>
		</location>
	</locations>
</subscriber>
