=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc2-WS/Lab3-WSConnectorServlet-Solution/Web/sales.xsd
<?xml version="1.0" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        xmlns:p="http://www.skilltop.com/cst6445/Lab3"
        targetNamespace="http://www.skilltop.com/cst6445/Lab3"
        elementFormDefault="qualified">
        
    <element name="sales" type="p:SalesType"/>
        
    <complexType name="SalesType">
        <sequence>
            <element name="customer" type="p:CustomerPurchasesType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="DetailsType">
    	<sequence>
            <element name="first" type="string" minOccurs="1" maxOccurs="1" />
            <element name="last" type="string" minOccurs="1" maxOccurs="1" />
            <element name="email" type="string" minOccurs="1" maxOccurs="1" />
            <element name="custid" type="integer" minOccurs="1" maxOccurs="1" />
    	</sequence>
    </complexType>

    <complexType name="CustomerPurchasesType">
        <sequence>
            <element name="details" type="p:DetailsType" minOccurs="1" maxOccurs="1" />
            <element name="purchases" minOccurs="0" maxOccurs="1">
               <complexType>
                  <sequence>
                     <element name="purchase" type="p:PurchaseType" minOccurs="1" maxOccurs="unbounded"/>
                  </sequence>
               </complexType>
            </element>
        </sequence>
    </complexType>


    <complexType name="PurchaseType">
        <sequence>
	    <element name="item" type="string" minOccurs="1" maxOccurs="1" />
	    <element name="description" type="string" minOccurs="1" maxOccurs="1" />
	    <element name="cost" type="decimal" minOccurs="1" maxOccurs="1" />
	</sequence>
    </complexType>
    
</schema>

=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc2-WS/Lab3-WSConnectorServlet-Solution/Web/sales.xml
<?xml version="1.0" encoding="utf-8" ?>
<sales xmlns="http://www.skilltop.com/cst6445/Lab3"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.skilltop.com/cst6445/Lab3 sales.xsd">
	<customer>
		<details>
			<first>John</first>
			<last>Smith</last>
			<email>jsmith@xyz.ca</email>
			<custid>424242</custid>
		</details>
		<purchases>
			<purchase>
				<item>Foo</item>
				<description>A foo for all occasion.</description>
				<cost>6.45</cost>
			</purchase>
			<purchase>
				<item>Bar</item>
				<description>Bar none!</description>
				<cost>10.88</cost>
			</purchase>
		</purchases>
	</customer>
	<customer>
		<details>
			<first>Fred</first>
			<last>Flintstone</last>
			<email>fred@storm.ca</email>
			<custid>100362</custid>
		</details>
		<purchases>
			<purchase>
				<item>Frobnotz</item>
				<description>I dont know what this is.</description>
				<cost>9.99</cost>
			</purchase>
		</purchases>
	</customer>
</sales>
