=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc3-WS-night6/D-tmp/bookstore.dtd
<?xml version="1.0" encoding="us-ascii"?>
<!ELEMENT bookstore (book*)>
<!ELEMENT book (author, title, genre, quantity)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== robdmorton/java_source1of1/EnterpriseJavaDeveloperCourseAlgonquinCollege/JavaMisc2-WS/Lab4-BookStore-Exercise/Web/bookstore.xml
<!DOCTYPE bookstore SYSTEM "http://localhost:8080/Lab4-BookStore-Exercise/bookstore.dtd">
<bookstore>
	<book>
		<author>A. Nonymous Esq.</author>
		<title>Some Intriguing Title</title>
		<genre>Fiction</genre>
		<quantity>10</quantity>
	</book>
	<book>
		<author>Jeff Larstone</author>
		<title>Hello World!</title>
		<genre>Horror</genre>
		<quantity>0</quantity>
	</book>
	<book>
		<author>John Smith</author>
		<title>qwerty</title>
		<genre>Non Fiction</genre>
		<quantity>1</quantity>
	</book>
	<book>
		<author>Jane Doe</author>
		<title>123456</title>
		<genre>Romance</genre>
		<quantity>4</quantity>
	</book>
</bookstore>
